modLoader="javafml"
loaderVersion="[40,)"
license="GPLv3"

[[mods]]
modId="projecta"
version="${file.jarVersion}"
displayName="ProjectA"
logoFile="logo.png"
credits=""
authors="Quarris"
description='''
Some Magic Mod; I guess
'''
[[dependencies.projecta]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projecta]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
